ORG 0000H;                    SETTING THE ORIGIN FOR USING MICRO CONTROLLER
MOV TMOD,#02H;                SELECTING TIMER 0 AND MODE 2
LOOP1:
SETB P1.4;                    LOGIC HIGH
ACALL DELAY;                  CALLING THE DELAY FUNC
CLR P1.4;                     LOGIC LOW
ACALL DELAY;                  CALLING THE DELAY FUNC
JMP LOOP1;                    JUMP TO LOOP1 TO GENERATE CONTINOUS WAVE

DELAY:
SETB TR0;                     LOGIC HIGH
MOV TL0,#0A4H;                SET THE VALUE OF TIMER TL0 TO 0A4H
MOV TH0,#0A4H;                SET THE VALUE OF TIMER TH0 TO 0A4H
LOOP2:
JNB TF0,LOOP2;                JUMP IF THE BIT IS NOT SET
CLR TF0;                      CLEAR THE TIMER OVER FLOW BIT
CLR TR0;                      DESELECT THE TIMER FOR FUTURE USE
RET;                          RETURN 
END;
