ORG 0000H;SETTING THE ORIGIN

MOV TMOD,#20H;CHOOSING THE MODE 2 AND TIMER 1

LOOP1:

MOV P2,#0FFH;LOGIC HIGH

ACALL LOOP2;CALLING DELAY OF 50ms

MOV P2,#00H;LOGIC LOW

ACALL LOOP2;CALLING DELAY OF 50ms

JMP LOOP1;REPEATING THE PROCESS FOR CONTINOUS WAVE

LOOP2:

MOV R3,#04H;LOOPING FOR DELAY OF 50ms I.E,4x50=200

LOOP5:

MOV R2,#32h;FOR DELAY OF 50ms 

DELAY:

SETB TR1;SELECTING TIMER 1

MOV TL1,#1AH;SETTING THE VALUE OF TL1 OF TIMER 1 TO 1A

MOV TH1,#1AH;SETTING THE VALUE OF TH1 OF TIMER 1 TO 1A

LOOP3:

JNB TF1,LOOP3; JUMP IF BIT IS NOT SET TO LOOP3

CLR TR1;DESELECTING THE TIMER 1

CLR TF1;CLEARING OVERFLOW BIT OF TFO FOR FURTHER USE

DJNZ R2,DELAY;

DJNZ R3,LOOP5;

RET;


END;