ORG 0000H;              SELECTING THE ORIGIN FOR PROGRAM
MOV TMOD ,#00H;         SELECTING TIMER 0 IN MODE 0
LOOP1:
SETB P1.4;              LOGIC HIGH
ACALL DELAY_4MS;        CALLING DELAY_4ms FUNCTION
CLR P1.4;               LOGIC LOW
ACALL DELAY_3MS;        CALLING DELAY_3ms FUNCTION               
JMP LOOP1;              JUMP TO LOOP1 FOR CONTINOUS WAVE

DELAY_4MS:              ;DEFINING SUBROUTINE DEAY_4MS FOR 4ms DELAY
SETB TR0;               SELCTING TIMER 0
MOV TL0,#1AH;           MOVING 1AH TO TL0 OF TIMER 0
MOV TH0,#1AH;           MOVING 1AH TO TH0 OF TIMER 0
LOOP2:
JNB TF0,LOOP2;          JUMP IF THE TF0 BIT IS NOT SET TO LOOP2
CLR TR0;                DESELECT THE TIMER 0
CLR TF0;                CLEAR OVERFLOW FLAG OF TIMER 0 FOR FURTHER USE
RET;

DELAY_3MS:              ;DEFINING SUBROUTINE DEAY_3MS FOR 3ms DELAY
SETB TR0;               SELCTING TIMER 0
MOV TL0,#04H;           MOVING 04H TO TL0 OF TIMER 0
MOV TH0,#54H;           MOVING 54HH TO TL0 OF TIMER 0
LOOP3:
JNB TF0,LOOP3;          JUMP IF THE TF0 BIT IS NOT SET TO LOOP3
CLR TR0;                DESELECT THE TIMER 0
CLR TF0;                CLEAR OVERFLOW FLAG OF TIMER 0 FOR FURTHER USE
RET;

END;
